check index version before reindex fixes #2084

diff --git a/OpenGrok b/OpenGrok
--- a/OpenGrok
+++ b/OpenGrok
@@ -857,6 +857,20 @@ CreateRuntimeRequirements()
     fi
 }
 
+CheckIndexVersion()
+{
+    if [ ! -f "${XML_CONFIGURATION}" ]
+    then
+        return
+    fi
+    if ! MinimalInvocation --checkIndexVersion -R "${XML_CONFIGURATION}" -d "${DATA_ROOT}"
+    then
+        echo "\nIndex version check failed. You might want to remove all data" \
+            "under the data root directory ${DATA_ROOT} and reindex.\n"
+        exit 1
+    fi
+}
+
 MinimalInvocation()
 {
     ${DO} ${JAVA} ${JAVA_OPTS} ${PROPERTIES}                    	\
@@ -892,7 +906,7 @@ CommonInvocation()
 StdInvocation()
 {
     CommonInvocation		\
-        -W ${XML_CONFIGURATION}	\
+        -W "${XML_CONFIGURATION}"	\
 	${SCAN_FOR_REPOSITORY}	\
 	${ENABLE_PROJECTS}	\
 	${DEFAULT_PROJECTS}	\
@@ -1057,12 +1071,14 @@ case "${1}" in
 
     update)
         ValidateConfiguration
+        CheckIndexVersion
         CreateRuntimeRequirements
         UpdateGeneratedData && UpdateDescriptionCache
         ;;
 
     updateQuietly)
         ValidateConfiguration
+        CheckIndexVersion
         CreateRuntimeRequirements
         QUIET="-q"
         VERBOSE=""
@@ -1089,6 +1105,7 @@ case "${1}" in
             SRC_ROOT="${2}"
         fi
         ValidateConfiguration
+        CheckIndexVersion
         CreateRuntimeRequirements
         UpdateGeneratedData && UpdateDescriptionCache
         ;;
@@ -1103,6 +1120,7 @@ case "${1}" in
 	    FatalError "need configuration via OPENGROK_READ_XML_CONFIGURATION"
 	fi
         ValidateConfiguration
+        CheckIndexVersion
         CreateRuntimeRequirements
         UpdateDataPartial $@
         ;;
