more style cleanup

diff --git a/OpenGrok b/OpenGrok
--- a/OpenGrok
+++ b/OpenGrok
@@ -136,7 +136,8 @@ DefaultInstanceConfiguration()
         else
             # Handle Binary Distributions
             OPENGROK_DISTRIBUTION_BASE="${SCRIPT_DIRECTORY}/../lib"
-            LOGGER_CONF_SOURCE="${OPENGROK_DISTRIBUTION_BASE}/../doc/${LOGGER_CONFIG_FILE}"
+            LOGGER_CONF_SOURCE="${OPENGROK_DISTRIBUTION_BASE}/../doc/"
+            LOGGER_CONF_SOURCE="${LOGGER_CONF_SOURCE}${LOGGER_CONFIG_FILE}"
         fi
     fi
 
@@ -188,7 +189,8 @@ DefaultInstanceConfiguration()
 
     # DEVELOPMENT: Debug option, if enabled current indexer will listen on the
     # port 8010 until a debugger connects
-    #JAVA_DEBUG="-agentlib:jdwp=transport=dt_socket,server=y,address=8010,suspend=y"
+    #JAVA_DEBUG="-agentlib:jdwp=transport=dt_socket"
+    #JAVA_DEBUG="$JAVA_DEBUG,server=y,address=8010,suspend=y"
 
     # OPTIONAL: Ignore these patterns as names of files or directories
     #IGNORE_PATTERNS="-i dummy"
@@ -353,9 +355,11 @@ Error()
 
 FatalError()
 {
-    echo 1>&2
-    echo "FATAL ERROR: ${@} - Aborting!" 1>&2
-    echo 1>&2
+    exec >&2
+    echo ""
+    echo "FATAL ERROR: ${@} - Aborting!"
+    echo ""
+
     ${DO} exit 2
 }
 
@@ -837,11 +841,13 @@ case "${1}" in
     deploy)
         DeployWar
         ;;
+
     derby)
         ValidateConfiguration
         CreateRuntimeRequirements
         DerbyServer
         ;;
+
     update)
         ValidateConfiguration
         CreateRuntimeRequirements
