windows
fixes #2822

diff --git a/dev/before_install b/dev/before_install
--- a/dev/before_install
+++ b/dev/before_install
@@ -35,6 +35,17 @@ if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
 		echo "cannot install Python packages"
 		exit 1
 	fi
+
+	# We only need to preserve TRAVIS_OS_NAME but older sudo do not
+	# support argument to --preserve-env.
+	sudo --preserve-env ./dev/install-universal_ctags.sh
+	if [[ $? != 0 ]]; then
+		echo "cannot install Universal ctags"
+		exit 1
+	fi
+
+	# for API blueprint verification
+	npm install drafter
 elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
 #	brew update
         export HOMEBREW_NO_AUTO_UPDATE=1
@@ -53,13 +64,28 @@ elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
 		echo "cannot install Python packages"
 		exit 1
 	fi
-fi
 
-sudo ./dev/install-universal_ctags.sh
-if [[ $? != 0 ]]; then
-	echo "cannot install Universal ctags"
-	exit 1
-fi
+	# We only need to preserve TRAVIS_OS_NAME but older sudo do not
+	# support argument to --preserve-env.
+	sudo --preserve-env ./dev/install-universal_ctags.sh
+	if [[ $? != 0 ]]; then
+		echo "cannot install Universal ctags"
+		exit 1
+	fi
+elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
+	choco install jdk8 -params 'installdir=c:\\jdk' -y
+	export JAVA_HOME=${JAVA_HOME:-/c/jdk}
+	export PATH=${JAVA_HOME}/bin:${PATH}
 
-# for API blueprint verification
-npm install drafter
+	choco install maven
+
+	choco install universal-ctags
+	export PATH=${PATH}:/c/ProgramData/chocolatey/lib/universal-ctags/tools
+
+	choco install svn
+	export PATH=${PATH}:/c/Program\ Files\ \(x86\)/Subversion/bin
+
+	choco install python3
+	# needs to be before the default Python 2
+	export PATH=/c/Python38:${PATH}
+fi
