add error checking

diff --git a/dev/before_install b/dev/before_install
--- a/dev/before_install
+++ b/dev/before_install
@@ -2,7 +2,15 @@
 
 if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
 	sudo apt-get update -qq
+	if [[ $? != 0 ]]; then
+		echo "cannot update"
+		exit 1
+	fi
 	sudo apt-get install -qq cvs git mercurial cssc bzr subversion monotone rcs rcs-blame python3 python3.4-venv python3-pip pep8 nodejs
+	if [[ $? != 0 ]]; then
+		echo "cannot install extra packages"
+		exit 1
+	fi
 	sudo ./dev/install-bitkeeper.sh
 	sudo pip3 install --upgrade pip
 	sudo pip3 install flake8
